[project]
name = "yolo-poetry"
version = "0.1.0"
description = ""
authors = [
    {name = "saadazhar7G",email = "saad.azhar@granlund.fi"}
]
readme = "README.md"
requires-python = ">=3.9.0"
dependencies = [
    "ultralytics (>=8.3.240,<9.0.0)",
    "opencv-python-headless (>=4.12.0.88,<5.0.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "typer (>=0.12.0,<1.0.0)",
    "pydantic (>=2.0.0,<3.0.0)",
    "pydantic-settings (>=2.0.0,<3.0.0)"
]

[tool.poetry]
packages = [{include = "yolo_poetry", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
